#pragma once
#include <iostream>
#include <string>
#include <ctime>
#include <vector>
#include <fstream>
#include <chrono>
#include <ctime>
#include <bitset>
#include <sstream>
#include <array>
#include <cstring>
#include <iomanip>
#include <random>
#include <cassert>
#include <stack>
#include <cstdlib>
#include <unistd.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <gmp.h>
#include <gmpxx.h>
#include <NTL/ZZ.h>
#include <NTL/mat_ZZ.h>
#include <NTL/matrix.h>
#include <NTL/vec_vec_ZZ.h>

