#pragma once
#include <iostream>
#include <ctime>
#include <vector>
#include <fstream>
#include <chrono>
#include <ctime>
#include <NTL/ZZ.h>
#include <NTL/mat_ZZ.h>
#include <NTL/matrix.h>
#include <NTL/vec_vec_ZZ.h>
