#pragma once
#include <iostream>
#include <string>
#include <ctime>
#include <vector>
#include <fstream>
#include <chrono>
#include <ctime>
#include <bitset>
#include <stdlib.h>
#include <sstream>
#include <array>
#include <cstring>
#include <iomanip>
#include <gmpxx.h>
#include <NTL/ZZ.h>
#include <NTL/mat_ZZ.h>
#include <NTL/matrix.h>
#include <NTL/vec_vec_ZZ.h>
